db:
 host: "localhost"
 port: "3306"
 user: "root"
 pass: "root0728"
 dbName: "simpledb"
 
 
http:
 port: "8081"
 
sf:
 userName: "sonia.chauhan259@gmail.com"
 pass: "7456893157@S"
 token: "f60DNYOerh3dy87d97SamdJN"
 
email:
 host: "smtp.gmail.com"
 port: "587"
 user: "fulfillment@apisero.com"
 pass: "ApiseroDev@2020"